### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by danividanivi** [gjgordon/SourcePanelMethod#1]
First of all, thanks for sharing your code.

I have one doubt:

As X and Y, do I have to enter a set of points or functions?
In case of having to put points, should I choose the open or closed coordinates?

I have to do it for a university project for NACA 0012 and I want to compare the results.

**Comment by dappersnowman** [comment]
For x and y, yeah, you have to input a set of points that defines the shape of your airfoil. A good example would be the coordinates that you get from airfoiltools.com.

http://airfoiltools.com/airfoil/details?airfoil=n0012-il

^That's the link to the NACA 0012 airfoil. Download the .dat file, clean up the header and you can import those coordinates directly into Matlab. If you get an interpolation error, make sure you check your coordinates to see if there's more than one set of (0,0) coordinates and delete the second one.

To be honest, I just tried to run my function on the NACA 0012 and got an error. I guess there were some bugs that I didn't completely knock out when I first posted this. If I fix it I'll publish a patch and make sure you hear about it.

Good luck on your project! I hope you don't slave over it like I did when I wrote this for my college project.
